server:
  port: 9191

spring:
  application: 
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/